/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * FreeLLM Gateway API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatCompletionRequest,
  ChatCompletionResponse,
  GatewayError,
  GatewayStatus,
  HealthStatus,
  ModelsResponse,
  ProviderStatus,
  UpdateProviderRequest,
  UpdateRoutingStrategyRequest,
} from "./schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns all models available across configured providers
 * @summary List available models
 */
export const getListModelsUrl = () => {
  return `/api/v1/models`;
};

export const listModels = async (
  options?: RequestInit,
): Promise<ModelsResponse> => {
  return customFetch<ModelsResponse>(getListModelsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListModelsQueryKey = () => {
  return [`/api/v1/models`] as const;
};

export const getListModelsQueryOptions = <
  TData = Awaited<ReturnType<typeof listModels>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listModels>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListModelsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listModels>>> = ({
    signal,
  }) => listModels({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listModels>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListModelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listModels>>
>;
export type ListModelsQueryError = ErrorType<unknown>;

/**
 * @summary List available models
 */

export function useListModels<
  TData = Awaited<ReturnType<typeof listModels>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listModels>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListModelsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * OpenAI-compatible chat completion endpoint with automatic provider failover
 * @summary Create chat completion
 */
export const getCreateChatCompletionUrl = () => {
  return `/api/v1/chat/completions`;
};

export const createChatCompletion = async (
  chatCompletionRequest: ChatCompletionRequest,
  options?: RequestInit,
): Promise<ChatCompletionResponse> => {
  return customFetch<ChatCompletionResponse>(getCreateChatCompletionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chatCompletionRequest),
  });
};

export const getCreateChatCompletionMutationOptions = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChatCompletion>>,
    TError,
    { data: BodyType<ChatCompletionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChatCompletion>>,
  TError,
  { data: BodyType<ChatCompletionRequest> },
  TContext
> => {
  const mutationKey = ["createChatCompletion"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChatCompletion>>,
    { data: BodyType<ChatCompletionRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createChatCompletion(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChatCompletionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChatCompletion>>
>;
export type CreateChatCompletionMutationBody = BodyType<ChatCompletionRequest>;
export type CreateChatCompletionMutationError = ErrorType<GatewayError>;

/**
 * @summary Create chat completion
 */
export const useCreateChatCompletion = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChatCompletion>>,
    TError,
    { data: BodyType<ChatCompletionRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createChatCompletion>>,
  TError,
  { data: BodyType<ChatCompletionRequest> },
  TContext
> => {
  return useMutation(getCreateChatCompletionMutationOptions(options));
};

/**
 * Returns provider health, circuit breaker states, and request metrics
 * @summary Gateway status
 */
export const getGetGatewayStatusUrl = () => {
  return `/api/v1/status`;
};

export const getGatewayStatus = async (
  options?: RequestInit,
): Promise<GatewayStatus> => {
  return customFetch<GatewayStatus>(getGetGatewayStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetGatewayStatusQueryKey = () => {
  return [`/api/v1/status`] as const;
};

export const getGetGatewayStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getGatewayStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getGatewayStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGatewayStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGatewayStatus>>
  > = ({ signal }) => getGatewayStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGatewayStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetGatewayStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGatewayStatus>>
>;
export type GetGatewayStatusQueryError = ErrorType<unknown>;

/**
 * @summary Gateway status
 */

export function useGetGatewayStatus<
  TData = Awaited<ReturnType<typeof getGatewayStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getGatewayStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetGatewayStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Manually reset a provider's circuit breaker to closed state
 * @summary Reset circuit breaker
 */
export const getResetProviderCircuitBreakerUrl = (providerId: string) => {
  return `/api/v1/status/providers/${providerId}/reset`;
};

export const resetProviderCircuitBreaker = async (
  providerId: string,
  options?: RequestInit,
): Promise<ProviderStatus> => {
  return customFetch<ProviderStatus>(
    getResetProviderCircuitBreakerUrl(providerId),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getResetProviderCircuitBreakerMutationOptions = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetProviderCircuitBreaker>>,
    TError,
    { providerId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetProviderCircuitBreaker>>,
  TError,
  { providerId: string },
  TContext
> => {
  const mutationKey = ["resetProviderCircuitBreaker"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetProviderCircuitBreaker>>,
    { providerId: string }
  > = (props) => {
    const { providerId } = props ?? {};

    return resetProviderCircuitBreaker(providerId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetProviderCircuitBreakerMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetProviderCircuitBreaker>>
>;

export type ResetProviderCircuitBreakerMutationError = ErrorType<GatewayError>;

/**
 * @summary Reset circuit breaker
 */
export const useResetProviderCircuitBreaker = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetProviderCircuitBreaker>>,
    TError,
    { providerId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof resetProviderCircuitBreaker>>,
  TError,
  { providerId: string },
  TContext
> => {
  return useMutation(getResetProviderCircuitBreakerMutationOptions(options));
};

/**
 * Enable or disable a provider for routing (operator control)
 * @summary Update provider
 */
export const getUpdateProviderUrl = (providerId: string) => {
  return `/api/v1/status/providers/${providerId}`;
};

export const updateProvider = async (
  providerId: string,
  updateProviderRequest: UpdateProviderRequest,
  options?: RequestInit,
): Promise<ProviderStatus> => {
  return customFetch<ProviderStatus>(getUpdateProviderUrl(providerId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProviderRequest),
  });
};

export const getUpdateProviderMutationOptions = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProvider>>,
    TError,
    { providerId: string; data: BodyType<UpdateProviderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProvider>>,
  TError,
  { providerId: string; data: BodyType<UpdateProviderRequest> },
  TContext
> => {
  const mutationKey = ["updateProvider"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProvider>>,
    { providerId: string; data: BodyType<UpdateProviderRequest> }
  > = (props) => {
    const { providerId, data } = props ?? {};
    return updateProvider(providerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProviderMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProvider>>
>;
export type UpdateProviderMutationBody = BodyType<UpdateProviderRequest>;
export type UpdateProviderMutationError = ErrorType<GatewayError>;

/**
 * @summary Update provider
 */
export const useUpdateProvider = <
  TError = ErrorType<GatewayError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProvider>>,
    TError,
    { providerId: string; data: BodyType<UpdateProviderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProvider>>,
  TError,
  { providerId: string; data: BodyType<UpdateProviderRequest> },
  TContext
> => {
  return useMutation(getUpdateProviderMutationOptions(options));
};

/**
 * Change the routing strategy used for provider selection
 * @summary Update routing strategy
 */
export const getUpdateRoutingStrategyUrl = () => {
  return `/api/v1/status/routing`;
};

export const updateRoutingStrategy = async (
  updateRoutingStrategyRequest: UpdateRoutingStrategyRequest,
  options?: RequestInit,
): Promise<GatewayStatus> => {
  return customFetch<GatewayStatus>(getUpdateRoutingStrategyUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateRoutingStrategyRequest),
  });
};

export const getUpdateRoutingStrategyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRoutingStrategy>>,
    TError,
    { data: BodyType<UpdateRoutingStrategyRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRoutingStrategy>>,
  TError,
  { data: BodyType<UpdateRoutingStrategyRequest> },
  TContext
> => {
  const mutationKey = ["updateRoutingStrategy"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRoutingStrategy>>,
    { data: BodyType<UpdateRoutingStrategyRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return updateRoutingStrategy(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRoutingStrategyMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRoutingStrategy>>
>;
export type UpdateRoutingStrategyMutationBody =
  BodyType<UpdateRoutingStrategyRequest>;
export type UpdateRoutingStrategyMutationError = ErrorType<unknown>;

/**
 * @summary Update routing strategy
 */
export const useUpdateRoutingStrategy = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRoutingStrategy>>,
    TError,
    { data: BodyType<UpdateRoutingStrategyRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateRoutingStrategy>>,
  TError,
  { data: BodyType<UpdateRoutingStrategyRequest> },
  TContext
> => {
  return useMutation(getUpdateRoutingStrategyMutationOptions(options));
};
